### PR TITLE
Updated docs to mention dropzone timeout.

### PR DESCRIPTION
**Pull request by Abijeet**
Towards BookStackApp/BookStack#876

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Thanks @Abijeet.

Notes, to do before merge (I'm happy to do this btw, Just putting here as a reminder):

* Update variable to `uploadTimeout`
* Relate to https://www.bookstackapp.com/docs/admin/upload-limits/ page.

**Comment by Abijeet** [comment]
Hey @ssddanbrown - I've updated the https://www.bookstackapp.com/docs/admin/visual-customisation/ page, but not sure how best to relate these with https://www.bookstackapp.com/docs/admin/upload-limits/ page.

Should I add a section called further customization under upload-limits and link it to this heading?

**Comment by ssddanbrown** [comment]
Thanks @Abijeet, Yeah it's a bit tricky to organise this in a sensible way. I'll have a play, might make the different pages more defined.

**Comment by ssddanbrown** [comment]
Created a specific file uploads section in the end which then this fits perfectly into:
https://www.bookstackapp.com/docs/admin/upload-config/

Visual-customization page has been cleaned up to focus on visual elements.

**Pull request merged**
