### PR TITLE
docs: Add Easypanel as a deployment method 

### PR DESCRIPTION
**Pull request by berksmbl**

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Thanks for offering this @berksmbl, but I wouldn't want to list a third party resource as it's own section like this, since it infers officially recommendation/support. 

I'd be happy to have a simple entry added to the ["Other Hosting Options"](https://www.bookstackapp.com/docs/admin/installation/#other-hosting-options) section though.

**Comment by berksmbl** [comment]
> Thanks for offering this @berksmbl, but I wouldn't want to list a third party resource as it's own section like this, since it infers officially recommendation/support.

Hello, Actually Easypanel is not a hosting solution. It is a management panel that you currently host on your own server and docker runs container in the background and allows you to manage them effortlessly. Templates are created by the community and allow for one-click installation.

**Comment by berksmbl** [comment]
> Thanks for offering this @berksmbl, but I wouldn't want to list a third party resource as it's own section like this, since it infers officially recommendation/support.

Hello @ssddanbrown, Actually Easypanel is not a hosting solution. It is a management panel that you currently host on your own server and docker runs container in the background and allows you to manage them effortlessly. Templates are created by the community and allow for one-click installation.

**Comment by ssddanbrown** [comment]
@berksmbl Sure, but it's still a third-party option for hosting BookStack. Doesn't have to specifically be a hosting service provider to be part of that list.

**Comment by ssddanbrown** [comment]
Thanks @berksmbl!

**Pull request merged**
