### PR TITLE
Update upload-config.md

### PR DESCRIPTION
**Pull request by hacmieu**
Non-Amazon, S3 Compatible Services add S3_REGION (Wasabi need)

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Hi @hacmieu,
Thanks for offering this but can you explain why this is needed?
I'd prefer to explain the use-case of this rather than a note for a specific platform, in case it helps use with alternative systems.
As far as I can see, after a quick scan, I though the region is mainly used in deciding the S3 endpoint which is manually defined anyway for non-S3, S3-like platforms.

**Comment by hacmieu** [comment]
> Hi @hacmieu, Thanks for offering this but can you explain why this is needed? I'd prefer to explain the use-case of this rather than a note for a specific platform, in case it helps use with alternative systems. As far as I can see, after a quick scan, I though the region is mainly used in deciding the S3 endpoint which is manually defined anyway for non-S3, S3-like platforms.

I have configured the bookstack to connect to Wasabi according to the instructions, but I can't connect to Wasabi. After turning on APP_DEBUG = true, I saw Wasabi saying wrong region so I added it. Everything runs fine.

**Comment by ssddanbrown** [comment]
Okay, What do you have configured as your `STORAGE_S3_ENDPOINT` value?

**Comment by ssddanbrown** [comment]
I'm going to go ahead and close this off. 
As touched upon above, I don't really want to be maintaining service-specific notes where possible.

**Pull request closed without merging**
