### PR TITLE
Adding another hosting option to docs

### PR DESCRIPTION
**Pull request by cosark**
Added a link to 1-click deploy template at repocloud.io efficient cloud hosting service

### CODE REVIEW

**Comment by ssddanbrown** [comment]
Thanks for offering this @cosark.

I'm not going to reject this out-right, but I'm going to let it sit for a while since there are a few amber flags here that make me wary of linking to the service from out docs, and I don't want to risk leading users to something potentially sketchy.
The flags include:

- The site/service looks quite newly created.
- There is no clear people/legal entity shown that's behind the service.
- It effectively lists some applications as open source, which are not (N8N, Outline as examples, which could raise some licensing queries here). 
- Use of AI for help, and likely to generate the descriptions for each project, increases the chance this is intended to be a low-effort AI-based grift in this space.

**Comment by cosark** [comment]
- Yes it's newly created
- We're a US based entity
- If you google "one-click deploy [app name in question]" you'll see this is a common practice. Open source apps are developed by the community in good faith. The whole idea is that we're able to self-host apps.
- That's a non sequitur. Do you have any logic that would connect AI generated content with the negative characterization you're making? Or is this something emergent from your own personal emotions? 

I think the community would appreciate you being objective. And you're at liberty to close this if you feel like your community is better served by your censorship to protect them, as a benevolent big brother of sorts. I respect whatever decision you make.

**Comment by ssddanbrown** [comment]
> If you google "one-click deploy [app name in question]" you'll see this is a common practice. 

I'm not questioning that, but I get wary of applications listed under the heading of being "open source" when they are not, especially by hosting providers where those differences can matter.

> Do you have any logic that would connect AI generated content with the negative characterization you're making? Or is this something emergent from your own personal emotions?

Both I guess. There is an obvious recent trend of AI being used for grifts, and that has emotionally made me wary of projects heavily leaning on AI. Again, not saying your service is a grift, but I'd be in a default wary position until other factors can provide confidence.

> I think the community would appreciate you being objective.

I think they'd also appreciate not being led into potentially sketchy services by us accepting any link added via PR.

**Comment by cosark** [comment]
The apps you referenced have 100s of contributors. You're suggesting the public doesn't have the right to self host them? That's demonstrably false.

I don't know what you think a grift would entail here. It's a straightforward hosting service.

**Comment by ssddanbrown** [comment]
> The apps you referenced have 100s of contributors. You're suggesting the public doesn't have the right to self host them? That's demonstrably false.

I never stated that. I said they're not open source, which is the heading they're put under on your website.
Both projects set additional limitations via their licenses which moves them outside the common definition (OSD) of open source. These conditions could have implications on you providing them as a hosting provider.

**Comment by cosark** [comment]
You seem to have some confusion. If what you think is true were actually true, then other repos would agree with you. But nobody agrees with you. Those licenses apply to users of the app. For example, if a user (at RepoCloud or AWS or anywhere) decided to white label one of those into a private SaaS - that might violate certain terms. This is a hosting service, no different than any other.

**Pull request closed without merging**
